### ISSUE TITLE
请问FSC.py文件中的access_file和meet_file是怎么得到的？

### ISSUE THREAD

**Issue by wmcx913** [TXZhe/FSC#1]
![image](https://user-images.githubusercontent.com/45451635/61260656-a8874c80-a7b1-11e9-8e84-d3e2db67d5aa.png)
请问FSC.py文件中的access_file和meet_file是怎么得到的？ @TXZhe

**Comment by TXZhe** [comment]
access_file 是时变交互网络用户访问地点的记录文件，格式为：“用户编号，访问开始时间，访问持续时间，访问地点”；
meet_file 是时变交互网络用户交互事件的记录文件，格式为：“用户1编号，用户2编号，交互开始时间，交互持续时间，交互地点”。

**Comment by wmcx913** [comment]
好的，谢谢！
