### ISSUE TITLE
求助源代码

### ISSUE THREAD

**Issue by wmcx913** [TXZhe/FSC#2]
您好，我看到这个仓库应该是对应文章《Identifying familiar strangers in human encounter networks》，另一篇文章《Can multiple social ties help improve human location prediction?》与这篇文章的通讯作者相同，都是由同一个实验室发的，请问您那里有第二篇文章的源代码吗？或者您能帮我拿到源代码吗？我想用第二篇文章作为一个对照组实验，但是在github找不到源码，给通讯作者发邮件也没有回音。麻烦您了！

**Comment by TXZhe** [comment]
十分抱歉，我这并没有这些工作的源代码。这个仓库也是根据论文内容复现的工具。您还是应该向原作者索取源代码。
